# Generated by Django 5.0.6 on 2024-05-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_route', models.CharField(max_length=200)),
                ('new_route', models.CharField(max_length=100)),
                ('clicks', models.IntegerField()),
                ('fcreacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'turls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tusers',
                'managed': False,
            },
        ),
    ]
